version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      dbt:
        patterns: ["dbt-*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
